title: "AGUSTÍN VIERA" 
logo: #Si quisiera poner una foto, va entre "" pero nose como cambiar los sizes.
description: > # (<br> for line breaks)
  <br><br>
  Lic. en Administración de Empresas con perfil en Análisis de Datos & BI / Dipl. en Business Intelligence & Data Science.
  <br><br>
  En este Portafolio se presentan Proyectos con aplicaciones prácticas de aprendizaje en 
  Análisis & Visualización de Datos, Business Intelligence, Modelos de Machine Learning & Data Science.  
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/agustinviera/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: G-EV06VFJGVC # Google Analytics tracking ID 
